image: node:12.19-buster

stages:
  # - test
  - deploy

# test:
#   stage: test
#   script:
#     - npm install

deploy:dev:
  stage: deploy
  script:
    - echo "DEV DEPLOY - " $HEROKU_APP_DEV
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  only: 
    - deploy-dev

deploy:qa:
  stage: deploy
  script:
    - echo "QA DEPLOY - " $HEROKU_APP_QA
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_QA --api-key=$HEROKU_API_KEY
  only: 
    - deploy-qa

deploy:prd:
  stage: deploy
  script:
    - echo "PRD DEPLOY - " $HEROKU_APP_PRD 
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRD --api-key=$HEROKU_API_KEY
  only: 
    - tags
